services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    container_name: pomodoro-rpg-api
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    container_name: pomodoro-rpg-db
    ports:
      - ${DB_PORT}:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data