FROM golang:1.22 AS migrate

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/rubenv/sql-migrate/...@latest

CMD ["sh", "-c", "sql-migrate up -config=sql-migrate-config.yml -env=production"]